
environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release

build_script:
  - git submodule update --init
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
